name: Lint

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master, main, develop]

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Code Linting
        run: npm run lint